### ISSUE TITLE
Users will run into 401s without manually relogging in once the cookie has expired

### ISSUE THREAD

**Issue by Ramko9999** [rohanshiva/gitgame#115]
**Problem:**
Attempting to make any HTTP requests after the cookie has expired will result in 401s. To escape the 401s, the user has to reauthenticate, thereby receiving a new cookie.

**Solutions:**
1. We could automatically refresh the cookie in the code using a refresh token.
2. We could route back to the login screen when we run into 401s.

**Comment by rohanshiva** [comment]
I vote for 2, keep it simple for now.
