### ISSUE TITLE
Design Session for MVP

### ISSUE THREAD

**Issue by Ramko9999** [rohanshiva/gitgame#2]
MVP requirements:

Users should be able to enter their GitHub username and be able to receive a random code chunk from one of their repositories. They should be able to peek above and below the chunk in the file.

Basically, the client should POST to /session/new; the API creates a new session and returns the session id back to the client. The client should be able to retrieve the first code chunk with GET to /session/{session_id}, they should be able to peek up a code chunk with GET to /session/{session_id}&peek=above and GET to /session/{session_id}&peek=below should peek below a code chunk.

The API endpoints won't matter too much, since, in the long run, we will be moving to a Websockets based API.

Here is the UML design of the Session class and the different components:

![session_mvp-uml drawio](https://user-images.githubusercontent.com/41026856/140469107-ee73e5e5-cc0e-4cd5-9fff-5e43eed9f19f.png)

My goal was to create a design that will react to change easily. For instance, perhaps we start by only considering JavaScript code files, but now we want to add TypeScript code files (the system should be adaptable for this change). Moreover, the design should allow for better testing. There are a lot of classes, but I think this design will also make the transition to building V1 out easier.

@rohanshiva

**Comment by Ramko9999** [comment]
I would appreciate some feedback on this.

**Comment by rohanshiva** [comment]
I thought a `session` would have a `File` and the `File` should be responsible for all the file methods like `PeakUp`, `PeakDown`, and `GetCodeChunk`.

**Comment by Ramko9999** [comment]
> I thought a `session` would have a `File` and the `File` should be responsible for all the file methods like `PeakUp`, `PeakDown`, and `GetCodeChunk`.

I wanted to abstract away the logic of selecting a file and picking chunks in the file into a separate FileSelector class. There may be different ways of selecting files, and reading chunks of files, and I think moving that logic out of Session may make it more extensible. 

Moreover, these objects can be passed via dependency injection into the Session constructor.

**Comment by Ramko9999** [comment]
I will update the UML diagram using some python tool to generate the UML and close this issue.
